### ISSUE TITLE
Cannot read JBIG2 image: jbig2-imageio is not installed

### ISSUE THREAD

**Issue by starplanet** [levigo/jbig2-imageio#54] opened 2017-10-27 09:12 UTC
I download the newest pdfbox command line tools pdfbox-app-2.0.7.jar from [official website](https://pdfbox.apache.org/download.cgi) and levigo-jbig2-imageio-1.6.5.jar from search.maven.org.

When I use the following command to extract images from a pdf document which includes jbig2 images,  pdfbox tool will report error.

```
java -cp levigo-jbig2-imageio-1.6.5.jar -jar pdfbox-app-2.0.7.jar ExtractImages my.pdf
```
the error messages are like following:

```
org.apache.pdfbox.contentstream.PDFStreamEngine operatorException
Cannot read JBIG2 image: jbig2-imageio is not installed
```

**Comment by hehetown** [comment] 2017-10-28 12:36
JDK1.7   PDFbox2.07+levigo-jbig2-imageio2.0
//------------------------------------------------------------
//--------------------------------------------------------------
JDK1.6    PDFbox2.07+ levigo-jbig2-imageio 1.6.5 
 ImageIO.scanForPlugins();  //add this code             
 PDFRenderer renderer = new PDFRenderer(document);

**Comment by starplanet** [comment] 2017-10-29 03:13
Which java file could I add the patch to? I add 'ImageIO.scanForPlugins' to `pdfbox/src/main/java/org/apache/pdfbox/filter/JBIG2Filter.java`  in pdfbox-2.0.7 src, but it doesn't work.
```
    public DecodeResult decode(InputStream encoded, OutputStream decoded,
                                         COSDictionary parameters, int index) throws IOException
    {
        ImageIO.scanForPlugins()
        ImageReader reader = findImageReader("JBIG2", "jbig2-imageio is not installed");
        DecodeResult result = new DecodeResult(new COSDictionary());
        result.getParameters().addAll(parameters);

```

Then I try to add 'ImageIO.scanForPlugins' to 'tools/src/main/java/org/apache/pdfbox/tools/PDFToImage.java', It still doesn't work.
```
                // render the pages
                boolean success = true;
                endPage = Math.min(endPage, document.getNumberOfPages());
                ImageIO.scanForPlugins();
                PDFRenderer renderer = new PDFRenderer(document);

```

Can you tell more clearly?

**Comment by hehetown** [comment] 2017-10-29 03:58
When I convert the PDF file into a PNG image, the background print error message: Cannot read JBIG2 image: jbig2-imageio is not installed...........
PDFRenderer renderer = new PDFRenderer(document); 
Before this code call, I added the following code: imageio. scanForPlugins();
The problem is solved.  
`///////////////////////////////////////////////////////////////////`
```java
public void Test(String pdfPath){
	PDDocument document = null;
	boolean failed = false;
	File file = new File(pdfPath);
	System.out.println("Opening: "+file.getName());
	try{                   
		new FileOutputStream(new File(path, file.getName() + ".parseerror")).close();   
                document = PDDocument.load(file, (String)null);                   
                String outputPrefix = path + '/' + file.getName() + "-";        
		int numPages = document.getNumberOfPages();            
		if (numPages < 1) {                
			failed = true;                     
			System.out.println("file " + file.getName() + " has < 1 page");            
		} else {                 
				new File(path, file.getName() + ".parseerror").delete();               
		}                    
	       ImageIO.scanForPlugins(); //add this code              
		PDFRenderer renderer = new PDFRenderer(document);               
		for (int i = 0; i < numPages; i++)                 
		{                  
			Map map = new HashMap<String, String>();          
			String fileName = outputPrefix + (i + 1) + ".png";      
			BufferedImage image = renderer.renderImageWithDPI(i, 96); // Windows native DPI                        
                         ImageIO.write(image, "PNG", new File(fileName));          
                 }
            }catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
		}
	}
```

**Comment by hennejg** [comment] 2017-11-06 08:57
Please note that this GitHub project is related to just the JBIG2 decoder, therefore it is the wrong place to ask for help about the integration into PDFBox. 
However, this project is currently in the process of becoming being transferred under the PDFBox umbrella, including the required re-licensing from GPL to ASL. Future PDFBox releases will therefore most likely include the plugin, obviating the need to integrate it manually.

**Closed by hennejg** 2017-11-06 08:57 UTC

**Comment by asilverskold** [comment] 2019-03-28 11:21
Maybe I will help somebody..
add line to your code: 
 IIORegistry.getDefaultInstance().registerServiceProvider(new JBIG2ImageReaderSpi());
in order to ImageIO will register jbig2 plugin. or add jar file into class path (but it did not work for me) 
ImageIO.scanForPlugins();  - also didnot work for me..

**Comment by hennejg** [comment] 2019-03-28 15:05
@asilverskold thanks for your comment. However, please keep my comment from above in mind: the Plugin is now maintained under the Apache PDFBox umbrella. For downloads see https://pdfbox.apache.org/download.cgi

The maven coordinates of the latest Apache release are: 
```
<dependency>
  <groupId>org.apache.pdfbox</groupId>
  <artifactId>jbig2-imageio</artifactId>
  <version>3.0.2</version>
</dependency>
```
